### ISSUE TITLE
Dashboard + Portfolio

### ISSUE THREAD

**Issue by jeremiahkellick** [jeremiahkellick/legolas#5]
- [x] Users can buy and sell shares from the stock pages
- [x] Users can view their dashboard which shows their portfolio's performance
- [x] The dashboard contains a sidebar showing all the user's owned stocks

**Comment by xnanodax** [comment]
Consider creating the row of dots to show the open market hours for the stock (this only shows up for the 1D view)
robinhood:
![screen shot 2018-10-17 at 10 50 08 am](https://user-images.githubusercontent.com/20424731/47106108-9e242c00-d1fa-11e8-8391-f57f71f29c25.png)

Also, consider, adding more statistics about the amount change, percentage, and time that has elapsed!

legolas:
![screen shot 2018-10-17 at 10 50 59 am](https://user-images.githubusercontent.com/20424731/47106166-c449cc00-d1fa-11e8-9be4-59fb73da6374.png)


robinhood:
![screen shot 2018-10-17 at 10 50 52 am](https://user-images.githubusercontent.com/20424731/47106133-aed4a200-d1fa-11e8-8e74-ece3662534d1.png)

**Comment by xnanodax** [comment]
Core functionality and styling is done :)! Great job again!
